### ISSUE TITLE
確認

### ISSUE THREAD

**Issue by come1120** [Bit2Byte-inc/web-bit2bye_blog_bbb#1]
@sohei-taniguchi @ShioriUechi 

http://bit2byte.space/BBB/
http://bit2byte.space/BBB/wp-login.php

管理画面ユーザー名: BBB
管理画面パスワード : klgdkgmklmkfl_ll
メールアドレス：bbb@bit2byte.jp

こちらテストアップしましたので、お手すきで確認をお願いします。

**Comment by ShioriUechi** [comment]
@come1120 
確認しました！本当にありがとうございました...！！！！！言葉足らずだったかもしれませんがイメージ通りにしていただいて本当にありがたいです！

何点か調整いただきたいのですが、一旦デザインで調整したあと共有したXDデータにコメントを書き加えますので後ほどご確認宜しくお願いします。。

**Comment by come1120** [comment]
@ShioriUechi 上記修正し、テストサイトアップしましたので確認をお願いします！

**Comment by ShioriUechi** [comment]
@come1120 
ありがとうございます！！私はめちゃくちゃ良いと思います！！！！！

@sohei-taniguchi 
いかがでしょうか？

**Comment by sohei-taniguchi** [comment]
@come1120 @ShioriUechi 
一旦これで飛鳥さんに確認してもらいましょうか！
どのチャンネルだったか忘れましたが報告をお願いします〜
