### ISSUE TITLE
一覧ページレイアウト固定→ブラウザ幅変更によるエリアサイズの安定化

### ISSUE THREAD

**Issue by YoheiKoshino** [Bit2Byte-inc/web-bit2bye_blog_bbb#4]
1,カテゴリページの一覧のサイズを固定化します。
https://docs.google.com/presentation/d/1nobcsq4ysDgvydkQrxAi2DlHpKP_SQYD/edit#slide=id.p8

2,トップページは、カテゴリと日付をエリア下に固定にします。
https://docs.google.com/presentation/d/1nobcsq4ysDgvydkQrxAi2DlHpKP_SQYD/edit#slide=id.p9
------
3,トップページの一覧、読み込み後のブラウザ幅を変更すると背景がついてこない点を安定させてください。
https://docs.google.com/presentation/d/1nobcsq4ysDgvydkQrxAi2DlHpKP_SQYD/edit#slide=id.p10
https://docs.google.com/presentation/d/1nobcsq4ysDgvydkQrxAi2DlHpKP_SQYD/edit#slide=id.p11

4,トップと同じ要素である、レコメンドエリアも3と同じく安定化お願いします。
https://docs.google.com/presentation/d/1nobcsq4ysDgvydkQrxAi2DlHpKP_SQYD/edit#slide=id.p12
https://docs.google.com/presentation/d/1nobcsq4ysDgvydkQrxAi2DlHpKP_SQYD/edit#slide=id.p13

**Comment by come1120** [comment]
@YoheiKoshino @asuka023jp
http://bit2byte.space/BBB/
http://bit2byte.space/BBB/wp-login.php

ユーザー名: blog
パスワード: test

トップページ、カテゴリトップページ、レコメンドエリアのタイトルに文字制限をつけ、高さを合わせました。

**Comment by YoheiKoshino** [comment]
@come1120 こちらも良い感じですねー！画面が締まった気がします！公開お願いします！

**Comment by come1120** [comment]
@YoheiKoshino @asuka023jp @ShioriUechi 

https://bbb.bit2byte.co.jp/

こちら公開しました！
記事ページのコード表示も修正済みです。
来年のMTGでこちらの記入方法など共有できればと思います
