### ISSUE TITLE
メニュー変更

### ISSUE THREAD

**Issue by YoheiKoshino** [Bit2Byte-inc/web-bit2bye_blog_bbb#6]
・ニュースを一番左にする
・レポートをworksに変更

お願いします！

**Comment by come1120** [comment]
@YoheiKoshino @asuka023jp 
http://bit2byte.space/BBB/
http://bit2byte.space/BBB/wp-login.php

ユーザー名: blog
パスワード: test

- ヘッダーメニューを変更しました。

**Comment by YoheiKoshino** [comment]
@come1120 メニューOKです！公開お願いします！

**Comment by come1120** [comment]
@YoheiKoshino @asuka023jp @ShioriUechi

https://bbb.bit2byte.co.jp/

メニュー修正しました。
